spring:
  application:
    name: recycle
  datasource:
    url: jdbc:mysql://recycle.crwjs2gsf01q.us-east-1.rds.amazonaws.com:3306/recycle
    username: admin
    password: Password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 5000